version: 2.1

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Ensure backend infrastructure exist
          command: |
            aws configure set aws_access_key_id \
              $AWS_ACCESS_KEY_ID \
              --profile default
            aws configure set aws_secret_access_key \
              $AWS_SECRET_ACCESS_KEY \
              --profile default
            aws configure set region $AWS_DEFAULT_REGION \
              --profile default    
            cd .circleci
            pwd
            ls -la
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name my-stack
workflows:
  my_workflow:
    jobs:
      - create_infrastructure