version: 2.1

jobs:
  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["9b:e9:8c:65:51:fa:da:af:7e:39:ed:3d:4a:dd:bd:76"] # You can get this ID in the section where you registered the SSH Key
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible # install the dependencies needed for your playbook
      - run:
          name: Configure server
          command: |
            cd .circleci      
            pwd
            ls -la
            echo '15.207.84.141 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBF9ItHbCN+Jn4gwudfE5fBz6SOpwvVL/vf1e78kec4hz1X3Prp/ZfhXbE8abk5BoB+9nzJSluECNhwMwpEDxJGE=' >> ~/.ssh/known_hosts
            ansible-playbook -i inventory.txt main-remote.yml
            

workflows:
  my_workflow:
    jobs:
      - configure_infrastructure