Resources:
  Ec2Instance:
 
    Type: AWS::EC2::Instance
    Properties:
      SecurityGroups:
       - !Ref InstanceSecurityGroup
      KeyName: Anupam
      ImageId: ami-0cda377a1b884a1bc
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH accesss via port 22
      SecurityGroupIngress:
       - IpProtocol: tcp
         FromPort: 22
         ToPort: 22
         CidrIp: 0.0.0.0/0